# Generated by Django 5.0.4 on 2024-04-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farsnews',
            name='blob_link_of_content',
        ),
        migrations.AddField(
            model_name='farsnews',
            name='link_of_content',
            field=models.TextField(null=True, verbose_name='link_of_content'),
        ),
    ]
